### PR TITLE
7.4 Make sprint status checkbox as buttons

### PR DESCRIPTION
**Pull request by sub13**
This pull request was edited the second time!.
I've replaced radio buttons on simple buttons. You can see results on screenshoots and video. If i did something wrong or you have some offers, please write down.
New Screenshoots!:

New Link to video: https://drive.google.com/file/d/1auluDdsduh4RJz8_CP56ZL1Nhcf8wpLY/view?usp=sharing

### CODE REVIEW

**Review by SergeyMokin — CHANGES_REQUESTED** [review]
Would suggest to move these buttons to list page with text in buttons like "Complete" and "Start" sprint
On edit page won't have possibility set status

**Comment by sub13** [comment]
I've made corrections. Also, pull request was updated. Please look at the new.

**Review by desenzo — DISMISSED** [review]

**Comment by sub13** [comment]
I've made corrections in the second time. Also, pull request was updated, all screenshots and video were updated. Please look at the new.

**Review by desenzo — APPROVED** [review]

**Review by SergeyMokin — CHANGES_REQUESTED** [review]
Only one case, please remove or add borders on all buttons (when disabled contains borders, on active not)

**Comment by sub13** [comment]
I've made corrections in the third time. Also, pull request was updated, all screenshots and video were updated. Please look at the new.

**Review by SergeyMokin — DISMISSED** [review]

**Comment by SergeyMokin** [comment]
well done

**Review by Chmelya — APPROVED** [review]

**Review by desenzo — APPROVED** [review]

**Review by desenzo — APPROVED** [review]

**Review by Chmelya — APPROVED** [review]

**Review by SergeyMokin — APPROVED** [review]

**Pull request merged**
